# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Cover"
  description: A landing page type of block that fills the top of the page.
  icon: web
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: A title
  logo_image: /logo.svg
  subtitle: A subtitle
  text: Content
  col_id: warning
  background_image: /featured-background.jpg
  height: med
  byline: A byline
  link_down: bookshop:generic/link_down
  button: [bookshop:generic/button]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    label: Heading
    comment: Enter the main title.
    type: text
  logo_image:
    label: Logo Image
    comment: Select a Logo image.
    type: image
    options:
      uploads_dir: icons
  subtitle:
    label: Subtitle
    comment: Enter a capitalized subtitle.
    type: text
  text:
    label: Text Content
    comment: Enter the main text content for your cover block.
    type: markdown
  col_id:
    label: Background Color
    comment: Select a background color to be displayed if no background image is selected. The darkness of the background color controls the font color.
    type: select
    options:
      values:
        - primary
        - secondary
        - success
        - info
        - warning
        - danger
        - white
        - light
        - dark
        - blue
        - gray
        - orange
        - black
  background_image:
    label: Background Image
    comment: Select an image as the background. Otherwise background color will be displayed.
    type: image
  height:
    label: Cover Height
    comment: Select a height for the cover section.
    type: select
    options:
      values:
        - auto
        - min
        - med
        - full
        - max
  byline:
    label: Byline
    comment: A byline to be displayed in the bottom right corner.
    type: text


