# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Feature"
  description: A feature to be used inside a section.
  icon: add_link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icon: fas fa-cubes
  title: A title
  text: Some text
  link: 
    url: https://github.com/gohugoio/hugo
    url_text: Read More

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  icon: fas fa-cubes
  title: A title
  text: Some text
  link: 
    url: https://github.com/gohugoio/hugo
    url_text: Read More
  
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon:
    label: Icon
    comment: Set an icon using Font Awesome Icons. Include the prefix, 'fas' or 'fab' followed by your icon.
    type: text
  title:
    label: Title
    comment: The title for the feature.
    type: text
  text:
    label: Text
    comment: The main text content of the feature.
    type: markdown
  url:
    label: Url
    comment: The url of the page to link to.
    type: url
  url_text:
    label: Link Text
    comment: The text to be displayed for the clickable link.
    type: text

