# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description: A simple customizable button.
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icon: fa-arrow-alt-circle-right
  size: lg
  type: primary
  url: https://github.com/google/docsy-example
  text: Learn More


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  icon: fa-arrow-alt-circle-right
  size: lg
  type: primary
  url: https://github.com/google/docsy-example
  text: Learn More

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon:
    label: Icon
    comment: Add a Font Awesome icon to your button. Follows the format fas fa-cubes.
    type: text
  size:
    label: Size
    comment: Select a size for the button.
    type: select
    options:
      values:
        - sm
        - lg
  type:
    label: Type
    comment: Select a button type from Bootstrap.
    type: select
    options:
      values:
        - primary
        - secondary
        - success
        - warning
        - outline-primary
        - outline-secondary
        - outline-success
        - outline-warning
  url:
    label: Url
    comment: The url for the address the button links to.
    type: url
  text:
    label: Text
    comment: The inner text of the button.
    type: text
